name: Run Weather PDF Script

on:
  schedule:
    - cron: '30 11 * * *'  # Schedule to run daily at 7 AM Central Time (1 PM UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pdfkit PyPDF2 redmail requests

      - name: Run WeatherPDF2 script
        run: |
          python WeatherPDF/WeatherPDF2.py
        env:
          googlekey: ${{ secrets.googlekey }}
